# Generated by Django 4.0.3 on 2022-04-13 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asc_management', '0001_initial'),
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='StudentAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(max_length=15, null=True, unique=True)),
                ('othername', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('dob', models.DateField(null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='Student Profile Picture')),
                ('address', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asc_management.department')),
                ('end', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_session', to='asc_management.session')),
                ('start', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='start_session', to='asc_management.session')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asc_management.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asc_management.semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asc_management.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
